version: "3.9"
services:
  api:
    container_name: notimed-backend
    restart: always
    image: notimed-api
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
