version: "3.9"
services:
  notimed-api:
    container_name: notimed-backend
    restart: always
    env_file:
      - .env
    build: 
      context: .
      target: production
    ports:
      - "5050:3000"
    links:
      - mongo
  mongo:
    container_name: db
    image: mongo
    restart: always
    ports: 
        -   "27017:27017"
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
